SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 800

TABLE_BACKGROUND_COLOR = "lightgreen"

MAX_NUMBER_OF_TABLE_CARDS = 6

CARD_FONT_SIZE = 28
CARD_SUIT_FONT_SIZE = int(CARD_FONT_SIZE * 1.2)
CARD_CENTER_FONT_SIZE = int(CARD_FONT_SIZE * 2)

CARD_WIDTH = 100  # 5 * 78
CARD_HEIGHT = 140  # 7 * 78
HAND_CARD_SPACING = 10
TABLE_CARD_SPACING = 45

CARD_INNER_RECT_WIDTH_SCALE = 2
CARD_INNER_RECT_HEIGHT_SCALE = 1.8
CARD_INNER_RECT_THICKNESS = 1
CARD_CORNER_TEXT_MARGIN_LEFT = 2.5
CARD_CORNER_TEXT_MARGIN_TOP = 0
CARD_RADIUS = 5
CARD_BORDER = 1
CARD_DEFEND_ANGLE = -12.5

CARD_FONT_NAME = "Helvetica"  # "Helvetica" "Tahoma" "dejavuserif"
CARD_SUIT_FONT_NAME = "monospace"  # "Helvetica" "Tahoma" "dejavuserif"

CARD_BACKGROUND_COLOR = "white"
CARD_BORDER_COLOR = "LightSlateGray"
CARD_BORDER_HOVER_COLOR = "red"
CARD_BORDER_CLICK_COLOR = "blue"
CARD_INNER_COLOR = "white"
CARD_INNER_RECT_COLOR = "SlateGray"

CARD_TEXT_COLORS = {
    "♦": "red",
    "♣": "black",
    "♥": "red",
    "♠": "black",
}

SCREEN_TITLE = "Durak"
